"""Add ON DELETE CASCADE to foreign keys

Revision ID: e36b64dbb9d4
Revises: 6351f0a5439c
Create Date: 2024-09-05 15:01:33.195086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36b64dbb9d4'
down_revision = '6351f0a5439c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('products_ibfk_5', type_='foreignkey')
        batch_op.drop_constraint('products_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('products_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'countries', ['country_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'sports', ['sport_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'genders', ['gender_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_ibfk_1', 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_ibfk_3', 'countries', ['country_id'], ['id'])
        batch_op.create_foreign_key('products_ibfk_1', 'brands', ['brand_id'], ['id'])
        batch_op.create_foreign_key('products_ibfk_4', 'genders', ['gender_id'], ['id'])
        batch_op.create_foreign_key('products_ibfk_5', 'sports', ['sport_id'], ['id'])
        batch_op.create_foreign_key('products_ibfk_2', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
