"""Adding more datatype longitud on column email user table

Revision ID: e88409a8e6a5
Revises: e36b64dbb9d4
Create Date: 2024-09-05 15:24:28.057129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e88409a8e6a5'
down_revision = 'e36b64dbb9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_comment="The user's email, used for login and communication.",
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=500),
               type_=sa.String(length=128),
               existing_comment='The hashed password of the user.',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=500),
               existing_comment='The hashed password of the user.',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=120),
               existing_comment="The user's email, used for login and communication.",
               existing_nullable=False)

    # ### end Alembic commands ###
